export const signosZodiacales = [
  {
    name: "Aries",
    image: "https://firebasestorage.googleapis.com/v0/b/horoscopo-1f11d.appspot.com/o/zodiaco%2Faries.svg?alt=media&token=43e82fb2-4ab3-43ce-ad9e-603ea9f2aeba",
    text: "ARIES. Como buenos guerreros y conquistadores que sois, este año os pondrá a prueba. Vuestro planeta Marte se activará en no pocas ocasiones, os hará brillar en lo social y hará culminar la mayoría de los planes y objetivos que tenéis por delante. Nada escapará a vuestra ambición que será máxima en todos los aspectos. Es el año de la concreción y la estabilidad, la energía que pondréis en juego dará resultados asombrosos. Los mejores meses para ejercer dicho empuje están marcados planetariamente en los meses de febrero, 2ª quincena, todo marzo y abril, y especialmente la primera quincena de mayo. Junio y julio serán períodos donde obtendréis el resultado de vuestra lucha, podréis hacer gala de conquistas verdaderas, incluso en los temas de sentimientos. El dinero florecerá y hasta el azar estará de vuestra parte en agosto y septiembre. Aprovechar la primera mitad del año, de esa manera obtendréis un final de año muy productivo. El 2024 se os presenta muy dichoso y terminará siendo un ciclo que no olvidaréis por tiempo. ¡Manos a la obra, que el grado de éxito está este año en vuestras manos! Según la numerología astrológica, estos son los números que debéis tener en cuenta durante el nuevo año: 01 - 37 - 53 - 72.",
  },
  {
    name: "Tauro",
    image: "https://firebasestorage.googleapis.com/v0/b/horoscopo-1f11d.appspot.com/o/zodiaco%2Ftauro.svg?alt=media&token=233455db-fd72-4ad0-93cf-b504bef84d9a",
    text: "TAURO. Venus, vuestro planeta regente y diosa del amor, os empujará en este año a estabilizar completamente el mundo emocional y las relaciones. Os obligará a realizar una selección más estricta con los contactos y amistades, esto os facilitará el vivir nuevas experiencias que conllevarán un mejor estado anímico y equilibrio. Pondréis mucho énfasis en dar a conocer las básicas necesidades personales y exigir que el medio ambiente os corresponda. Enero, febrero y marzo, serán meses clave para dejar bien claro vuestra situación, el grado de magnetismo, expansión y brillantez al actuar, os hará merecedores de resultados muy beneficiosos. El ámbito financiero estará a favor, es un año donde lo material se verá facilitado y hasta las inversiones que hagáis estarán amparadas por la suerte. Abril y mayo os proveerá de una suerte y circunstancias muy favorables que no se deben desaprovechar. Este año se presenta cargado de emociones, sobre todo en lo romántico. Finales de junio y todo julio, os esperan situaciones románticas y pasionales de primer orden. En 2024 no habrá malas sorpresas, pero sí cambios radicales que vosotros mismo estabais deseando. Según la numerología astrológica, estos son los números que debéis tener en cuenta durante el nuevo año: 02 - 25 - 27 - 35.",
  },
  {
    name: "Géminis",
    image: "https://firebasestorage.googleapis.com/v0/b/horoscopo-1f11d.appspot.com/o/zodiaco%2Fgeminis.svg?alt=media&token=01903459-be84-4119-8dc3-29ab72e1d2be",
    text: "GÉMINIS. Vuestra natural necesidad de movimiento y cambios obtendrán en este año los estímulos necesarios para ver que, el nuevo ciclo, aportará muchas modificaciones de vida. Tanto en lo profesional como en lo social se producirán novedades que os harán cambiar objetivos y formas de vivir. Es un año de renovación no solo en el ambiente, notaréis que vuestro interior también se modifica. Cambiará la perspectiva de la vida, buscaréis nuevo alicientes a las necesidades emocionales, incluso los demás quedarán asombrados de la renovación personal que lograréis en el 2024. En marzo y en abril vuestra vida cambiará, se producirá y notaréis un antes y un después. A partir de ese momento el nuevo año cobrará para vosotros una nueva dimensión. Junio, julio y agosto os proveerá de una expansión sin límites en todo lo que iniciéis. Incluso, sobre todo en agosto, la diosa de la Fortuna estará muy cerca de vosotros. Este nuevo año aportará algo que de siempre añoráis, que el ambiente os estimule y que los objetivos se consigan a muy corto plazo. Vuestro magnetismo personal será de tal grado que, hasta los enemigos más acérrimos, claudicarán ante vosotros. Según la numerología astrológica, estos son los números que debéis tener en cuenta durante el nuevo año: 03 - 17 - 21 - 43.",
  },
  {
    name: "Cáncer",
    image: "https://firebasestorage.googleapis.com/v0/b/horoscopo-1f11d.appspot.com/o/zodiaco%2Fcancer.svg?alt=media&token=353ea1fd-1365-4b49-a90f-6a5680d81a66",
    text: "CÁNCER. Os espera un año relevante, potenciador y gratificante. Todos los sueños e ilusiones que os habéis marcado por tiempo, se verán plasmados en este nuevo ciclo. Estos resultados vendrá de la mano por una nueva actitud que proyectaréis en la vida. Haréis una selección más estricta de con quienes y cómo actuaréis en la vida. Serán fáciles los cambios y rentables los cambios, incluso profesionales. Enero, febrero y marzo, serán cruciales para esa nueva elección, incluso el azar, sobre todo en finales de febrero y primeros de marzo, os traerá buenas sorpresas. A partir de abril notaréis un fuerte empujón vital que os hará conquistar los objetivos con suma facilidad. En lo emocional los sentimientos estarán a tope, un especial magnetismo personal hará que el amor y las aventuras tengan una especial vibración y encanto. La unión que se consiga durará en el tiempo y cubrirá todas las esperanzas. Julio, septiembre y noviembre, serán meses especiales en vuestra expansión social y profesional. Es un año en el que los sueños se harán realidad, las circunstancias serán propicias y recibiréis el apoyo social, personal y familiar en todos vuestros proyectos. La actitud de no dudar en las propias capacidades, será la clave para un año triunfal. Según la numerología astrológica, estos son los números que debéis tener en cuenta durante el nuevo año: 04 - 13 - 37 - 47. ",
  },
  {
    name: "Leo",
    image: "https://firebasestorage.googleapis.com/v0/b/horoscopo-1f11d.appspot.com/o/zodiaco%2Fleo.svg?alt=media&token=bcc2b824-89d7-4443-9435-7f4d27d733be",
    text: 'LEO. En este nuevo año se pondrá a prueba tu natural capacidad de mando, lo iniciarás con una actitud observadora y selectiva hacia todo lo que te rodea. En tu mente estarán pasando ideas de cambio y restructuración en muchos aspectos de tu vida. El hacer gala de tu poder organizativo será la llave que te lleve a un éxito completo. Nadie más que tu sabe exactamente qué es lo que quiere y cómo lo quiere, todo ello se dará con más facilidad en los meses de febrero, abril, agosto y diciembre. Todo cambio que realices, incluso en lo profesional y emocional, dentro de esos meses, tendrá resultados muy favorables llegando a cambiar radicalmente tu vida. Finales de mayo y principios de junio, acontecerán circunstancias que te obligarán a tomar radicales decisiones, no dudes en hacerlo, tu intuición te guiará en todo momento. 2024 se os presenta como el año de la confirmación de vuestros reales valores y a los que sabréis defender y conquistar con suma astucia y seguridad. No es un ciclo para perder el tiempo en pequeñeces, debéis ir a por lo grande, los astros están de vuestra parte y, el "rugido" del león, se escuchará en todas partes. Según la numerología astrológica, estos son los números que debéis tener en cuenta durante el nuevo año: 05 - 10 - 25 - 43.',
  },
  {
    name: "Virgo",
    image: "https://firebasestorage.googleapis.com/v0/b/horoscopo-1f11d.appspot.com/o/zodiaco%2Fvirgo.svg?alt=media&token=e961eef7-cebe-4717-a4a3-7ad27a630021",
    text: 'VIRGO. Será el año que estéis en vuestra salsa, los límites solo los pondréis vosotros. Haced caso a vuestra intuición, no permitáis que terceros os confundan con caducos criterios, es el año en que vuestra propia esencia debe actuar firme y decidida. Ya los primeros meses, entre enero y mayo, los astros os pondrán por delante circunstancias que no debéis desaprovechar. Dejaros guiar por vuestro "duende interior" y asumir cualquier nueva responsabilidad, veréis que el campo, además de estar bien abonado, os dará resultados muy positivos en todo. En julio, septiembre y noviembre, hasta la diosa Fortuna estará atenta a daros una alegría. Este nuevo año se os presenta como el de la "buena siembra", todo aquello que aportéis, incluso desde el punto de vista de inversión, tendrá excelentes resultados. Los asuntos del amor y las relaciones, tendrán un giro importante, vuestro propio mundo interior, os llevará a ser más conscientes del valor entre lo que dais y recibís. Es un año "reestructural" en todos los sentidos, es el ciclo en donde los Virgo reforzarán sus cualidades naturales y conseguirán mayor estabilidad en todos los sentidos. Según la numerología astrológica, estos son los números que debéis tener en cuenta durante el nuevo año: 06 - 09 - 16 - 37.',
  },
  {
    name: "Libra",
    image: "https://firebasestorage.googleapis.com/v0/b/horoscopo-1f11d.appspot.com/o/zodiaco%2Flibra.svg?alt=media&token=61f03a4c-c2fa-4507-80c4-4751bebdf965",
    text: 'LIBRA. Entráis en un año en el que el aburrimiento no existirá, las sorpresas y los nuevos estímulos no faltarán. Vuestro planeta regente, Venus diosa del amor, jugará todo el tiempo como "al gato y al ratón". Nuevo año muy emocional, donde vuestro magnetismo, atractivo y seducción, serán las claves para el triunfo en muchos aspectos de la vida. Vuestra presencia mundana brillará con un color especial, es el año en que esa expansión social os llevará a realizar cambios en la profesión y en los sentimientos. Los meses de febrero, abril, junio y octubre, se presentan como los más aptos para conseguir cualquier plan o idea. Este nuevo ciclo vital os hará poneros las pilas en la consecución de objetivos, incluso los demás se quedarán asombrados ante vuestra nueva actitud en enfrentar la vida y las cosas. El año no solo traerá cambios en vuestra vida, lo hará mucho más profundamente en vuestro interior. El 2024 presenta una "balanza", símbolo de vuestro signo, mucho más equilibrada y con un fiel bien dirigido hacia vuestro crecimiento personal. No habrá fronteras para nada, siempre y cuando, en cuanto tengáis una idea o deseo claro, ir a por todas, caiga quien caiga. Según la numerología astrológica, estos son los números que debéis tener en cuenta durante el nuevo año: 07 - 11 - 19 - 43.',
  },
  {
    name: "Escorpio",
    image: "https://firebasestorage.googleapis.com/v0/b/horoscopo-1f11d.appspot.com/o/zodiaco%2Fescorpio.svg?alt=media&token=8ddccb0e-3fd8-47b8-b26a-0600550098d2",
    text: 'ESCORPIO. Un año apasionante, como a vosotros os gusta. El planeta Marte y Plutón son los regentes de vuestro signo, ambos asociados a la fuerza y el combate. El año no carecerá de posibilidades para que se ejerzan ambas cualidades. Por de pronto, desde un principio del 2024, notaréis que vuestra carga emocional se saldrá de los límites, tanto en el terreno profesional como en el de los sentimientos, vuestra ambición y dominio estarán muy potenciados. Las experiencias en el amor y la pasión serán múltiples y no habrá fronteras que os pare. Los meses de febrero, abril, julio y noviembre, serán los más aptos para conseguir la pareja ideal y las remuneraciones pertinentes en acciones profesionales. El 2024 se presenta como un año de avance y consecución de objetivos. Incluso los temas del azar os brindarán buenas sorpresas a partir de finales de enero hasta todo mayo. Todo está en vuestras manos el exigirle al tiempo abundancia, cuanto más os impliquéis en los objetivos deseados, mejores resultados se obtendrán. No será nada descartable que, en más de una ocasión, "perdáis la cabeza" por un amor apasionado que os hará vivir nuevas experiencias. Según la numerología astrológica, estos son los números que debéis tener en cuenta durante el nuevo año: 08 - 12 - 27 - 39.',
  },
  {
    name: "Sagitario",
    image: "https://firebasestorage.googleapis.com/v0/b/horoscopo-1f11d.appspot.com/o/zodiaco%2Fsagitario.svg?alt=media&token=c0a7272c-227b-4f35-ac39-7fa83bf7f54b",
    text: 'SAGITARIO. Año muy movido que os hará reflexionar, el "centauro" de vuestro signo se pondrá a trotar y la flecha seguro que dará en la diana. Es el ciclo donde lucharéis a capa y espada por los derechos que consideráis lógicos y obligatorios. Vuestro planeta Júpiter os empujará a resolver viejos asuntos materiales y de estabilidad. Entre enero y marzo las finanzas cobrarán un sentido superior y estaréis abocados a conquistar el máximo de bienestar en ello. Será en abril cuando obtendréis el excelente resultado de todo lo buscado. Nada ni nadie os detendrá para conseguir los fines, incluso postergaréis ciertos lazos emocionales, en la consecución de estos deseos. A partir de junio se pondrán las cosas más fáciles, circunstancias, asociaciones y un acentuado magnetismo os brindará en bandeja seguros triunfos. Es un año de reestructuración de vuestras vidas, le daréis el verdadero valor a las cosas y dispondréis de buena soltura económica y de acción. Septiembre y octubre se presentan como los meses de mayor avance, toda inversión y asociación que hagáis, aportará seguros beneficios. El 2024 os llega con aire renovador y en el que no cabe ninguna duda y temor ¡A por él con firmeza! Según la numerología astrológica, estos son los números que debéis tener en cuenta durante el nuevo año: 09 - 11 - 29 - 45.',
  },
  {
    name: "Capricornio",
    image: "https://firebasestorage.googleapis.com/v0/b/horoscopo-1f11d.appspot.com/o/zodiaco%2Fcapricornio.svg?alt=media&token=a5c03d5b-76f8-4807-94a8-b15bb723790b",
    text: 'CAPRICORNIO. Quedarán muy atrás las limitaciones del pasado año; el 2024 se presenta como el "recolector" de todo aquello deseado. Incluso en vuestro mundo emocional será un ciclo de equilibrio y compensación, se despiertan los romances y el consolidar las relaciones. Este año descubriréis quién y quiénes realmente están de vuestro lado. Vosotros mismos os asombraréis al descubrir que no estabais solos en la lucha. Vuestro planeta Saturno será más condescendiente, aportando estabilidad emocional e incluso material. Enero, marzo, mayo y sobre todo julio y septiembre, serán los meses que más rédito podréis sacar en todo. Hasta la diosa de la Fortuna se acercará a vosotros en julio y noviembre. Es un año para que no dudéis de vuestros naturales valores, no hará falta rigidez ni acciones precipitadas, la sola presencia vuestra, por un magnetismo personal muy acentuado, marcará las diferencias y corregirá el camino. El resultado del año será muy productivo, si estáis con el deseo de cambiar profundamente vuestras vidas, este es el año ideal. Desde el mismo comienzo del 2024, surgirán nuevos proyectos e ilusiones que, en los meses referidos, se harán realidad en toda su dimensión. Según la numerología astrológica, estos son los números que debéis tener en cuenta durante el nuevo año: 02 - 10 - 27 - 37.',
  },
  {
    name: "Acuario",
    image: "https://firebasestorage.googleapis.com/v0/b/horoscopo-1f11d.appspot.com/o/zodiaco%2Facuario.svg?alt=media&token=da68a260-cb2f-4946-a8d6-d5946cb22efb",
    text: "ACUARIO. Libertad, libertad y más libertad, pues sí, vuestro siempre ansiado deseo en encontrar el suficiente espacio para sentiros libres, lo conseguiréis en este nuevo año. Seguros cambios en lo profesional os hará encontrar el equilibrio deseado e incluso en el plano sentimental, se romperán ciertos atavismos y emprenderéis nuevos caminos y experiencias. Los meses de febrero, abril, junio y agosto, serán decisivos para el resto del año y de la vida en general. Vuestra imagen social y también familiar, maravillará a muchos. Urano, el planeta que os rige, se mostrará en toda su potencia, creará situaciones inesperadas que harán cambiar por completo vuestra existencia. Evitar y huir lo máximo posible a los miedos o temores ante las circunstancias, es el año en que la expansión a todos los niveles actuará en vuestras vidas. De los beneficios del azar no estaréis exentos, los meses de febrero, junio, agosto y diciembre son en los que la diosa de la Fortuna estará con vosotros. Claro está que, se os presenta un 2024 donde no habrá límites a todo aquello que busquéis conseguir, para ello, desprenderos de personas negativas y dejar que vuestra intuición marque los pasos a realizar ¡Un año de lanzamiento personal! Según la numerología astrológica, estos son los números que debéis tener en cuenta durante el nuevo año: 07 - 11 - 25 - 43.",
  },
  {
    name: "Piscis",
    image: "https://firebasestorage.googleapis.com/v0/b/horoscopo-1f11d.appspot.com/o/zodiaco%2Fpiscis.svg?alt=media&token=1d2045ee-99a5-4bf4-8985-f211385f8983",
    text: "PISCIS. Un nuevo año para que los sueños se hagan realidad. Vuestro planeta regente, Neptuno, resurgirá de los profundos mares de vuestra mente, para comprobar la total realización de los objetivos planteados. Familia y profesión acusarán cambios importantes y benéficos, ya en los inicios del año se percibe en vuestro interior, las ganas e ideas en producir modificaciones. Serán los meses de febrero, marzo, julio y septiembre, donde las condiciones serán óptimas para su realización. Incluso llegan beneficios por todo lo que conlleve a inversiones y hasta cambio de domicilio. El 2024 os favorece mucho en el terreno financiero y en el hacer valer las propias capacidades. Vuestra intuición será la clave y la llave maestra para hacer coincidir lo apropiado de las circunstancias y vuestro ojo cínico para aplicar el movimiento apropiado. Olvidaros este año de las recomendaciones de terceros, será vuestra firmeza y autodeterminación la que obtenga el mejor fruto en todo. Vuestra imagen social aumentará facilitando los éxitos, el fin de año estará colmado de aciertos si os centráis en objetivos claros y vais a por ellos. La Fortuna os persigue y a mitad de año se dejará notar. Según la numerología astrológica, estos son los números que debéis tener en cuenta durante el nuevo año: 05 - 12 - 19 - 47.",
  },
];
